# Generated by Django 2.2.6 on 2019-11-23 00:50

import apps.common.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=125, null=True)),
                ('content', models.TextField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=125, null=True, unique=True)),
                ('views', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.common.utils.photo_file_loc)),
                ('total_likes', models.PositiveSmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='images_liked', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ('-created',),
            },
        ),
    ]
