# Generated by Django 2.1.10 on 2019-11-29 14:35

import apps.common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20191123_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to=apps.common.utils.photo_file_loc),
        ),
    ]
